### PR TITLE
Package up coptr

### PR DESCRIPTION
**Pull request by Midnighter**
Hi,

First of all thank you for creating this cool. I'm testing it at the moment but it looks promising already!

I was a bit annoyed that coptr is not installable but has to be run from the script so I went ahead and fixed that. So in principle, with these changes, you can distribute coptr on PyPI and create a conda-forge feedstock. When the package is installed it creates a command line tool simply called `coptr`.

I see a number of things that can still be improved but this was the minimal workable thing for me. If you look at the individual commits, I hope you can follow what I did without being overwhelmed by all changes.

Please let me know if this is of interest to you.

### CODE REVIEW

**Comment by tyjo** [comment]
Thanks for the pull request! I am interested in merging this into the main branch.

I think it might be better to distribute CoPTR on bioconda or conda-forge rather than PyPI. PyPI doesn't appear to support dependencies that are not themselves Python packages---like bowtie2. Is there a reason you prefer conda-forge over bioconda?

**Comment by Midnighter** [comment]
> I think it might be better to distribute CoPTR on bioconda or conda-forge rather than PyPI. PyPI doesn't appear to support dependencies that are not themselves Python packages---like bowtie2.

While that is true, there are many Python packages that have other system dependencies. It is still very convenient to be able to `pip install` the package when one doesn't want to use conda and simply require that bowtie2 is installed on the system separately.

> Is there a reason you prefer conda-forge over bioconda?

In this case not really. Conda-forge builds packages for Linux, Mac, and Windows so that's an advantage when there are compiled components. Since that is not the case 🤷🏼‍♂️

**Comment by tyjo** [comment]
I merged this into the main branch and updated the documentation. I still need to look into distribution on PyPI / conda.

**Comment by Midnighter** [comment]
Let me know if you want some help with that. I maintain a number of packages both on PyPI and conda-forge so I'm quite familiar with the process.

**Comment by tyjo** [comment]
CoPTR is up on PyPI and installable via pip: https://pypi.org/project/coptr/

**Pull request merged**
